#
# Module manifest for module 'IntuneCosmosDBAccess'
#
# Generated by: Uma Parhar
#
# Generated on: 9/1/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'IntuneCosmosDBAccess.psm1'

# Version number of this module.
ModuleVersion = '1.0.2'

# Supported PSEditions
# CompatiblePSEditions = @()

# Author of this module
Author = 'Uma Parhar'

# Company or vendor of this module
CompanyName = 'Microsoft'

# Copyright statement for this module
Copyright = '(c) 2025 Uma Parhar. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Unified module for Intune Cosmos DB access management. Provides comprehensive functionality to query Kusto for Intune inventory details, generate JIT access commands for Cosmos DB resources, execute JIT access requests, and manage Azure role assignments for Cosmos DB access.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-IntuneInventoryDetails',
    'Set-IntuneKustoConfiguration',
    'New-IntuneCosmosJitAccess',
    'Invoke-IntuneE2ECosmosAccess',
    'Get-CosmosDBReadAccess',
    'Get-CosmosDBWriteAccess',
    'Revoke-CosmosDBAccess',
    'Test-AzCLI',
    'Get-PmeObjectId',
    'Check-JITShellInstallation',
    'Init-JITShell',
    'Request-JITAccess'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Intune', 'CosmosDB', 'JIT', 'Azure', 'Kusto', 'Access', 'Management', 'PowerShell')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial release of IntuneCosmosDBAccess module v1.0.0

Features:
- Query Kusto for Intune inventory details
- Generate JIT access commands for Cosmos DB resources
- Execute JIT access requests with polling for approval
- Manage Azure role assignments for Cosmos DB access
- Support for both read-only and read-write access
- End-to-end workflow automation
- PME authentication support
- Azure CLI integration'

    }

}
}
